@startuml Recipify

component frontend
component app.js
component openAIAPI
component EdamamAPI


frontend --> app.js: User inputs ingredients
app.js --> openAIAPI: query OpenAI API with ingredients
openAIAPI --> app.js: response with recipe names
app.js --> EdamamAPI: query Edamam API with recipe name
EdamamAPI --> app.js: response with recipe details
app.js --> frontend: display recipe details

@enduml